# Generated by Django 5.0.6 on 2024-09-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    # Marks this as the initial migration for the app
    initial = True
    # Specifies dependencies (none in this case, since it's an initial migration)
    dependencies = [
    ]
    # Defines the operations that will be applied to the database
    operations = [
        # Creates a new database model called 'Product'
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
